WIP - Flow/Javascript support
typed-wire/typed-wire pull request #16
Opened 2017-06-07 18:48 UTC by ajnsit

This is WIP code for generating Flow (https://flow.org) code from typed-wire (which can be used by javascript). It seems to work but has not been fully tested. The flow types are raw json objects with structure matching that of the json parsing/serialising code generated by typed-wire for other languages. This means that no special json serialiser/parser code generation is needed.

Please review / provide feedback.

2017-06-09 13:45 UTC, agrafix requested changes
Thank you very much for your pull request! I've added some comments, what do you think?

2017-06-09 13:45 UTC, agrafix commented on app/Main.hs
> +import Prelude
why is this needed?

2017-06-09 13:45 UTC, agrafix commented on src/TW/Ast.hs
> +import Prelude
why is this needed?

2017-06-09 13:45 UTC, agrafix commented on src/TW/BuiltIn.hs
> +import Prelude
why is this needed?

2017-06-09 13:45 UTC, agrafix commented on src/TW/Check.hs
> +import Prelude
why is this needed?

2017-06-09 13:45 UTC, agrafix commented on src/TW/CodeGen/Elm.hs
> +import Prelude
why is this needed?

2017-06-09 13:45 UTC, agrafix commented on src/TW/CodeGen/Flow.hs
> +import Prelude
why is this needed?

2017-06-09 13:45 UTC, agrafix commented on src/TW/CodeGen/Flow.hs
> +libraryInfo = LibraryInfo "Flow" "flow-typed-wire-utils" "0.1.0.0"
is this an npm library? is it needed for the generated output and where can I find the source?

2017-06-09 13:45 UTC, agrafix commented on src/TW/CodeGen/Flow.hs
> +          in unTypeName (sd_name sd) <> (if length (sd_args sd) > 0 then ("<" <> types <> ">") else types)
simpler: `if null (sd_args sd) then "" else ("<" <> types <> ">")`

2017-06-09 13:45 UTC, agrafix commented on src/TW/CodeGen/Flow.hs
> +    (unFieldName $ sf_name sf) <> " : " <> (makeType $ sf_type sf)
might we need some escaping here for reserved keywords, etc?

2017-06-09 13:45 UTC, agrafix commented on src/TW/CodeGen/Flow.hs
> +          in unTypeName (ed_name ed) <> (if length (ed_args ed) > 0 then ("<" <> types <> ">") else types)
This looks like code duplication from above. Can you extract that into a function?

2017-06-09 13:45 UTC, agrafix commented on src/TW/CodeGen/Haskell.hs
> +import Prelude
?

2017-06-09 13:45 UTC, agrafix commented on src/TW/CodeGen/PureScript.hs
> +import Prelude
?

2017-06-09 13:45 UTC, agrafix commented on src/TW/JsonRepr.hs
> +import Prelude
?

2017-06-09 13:45 UTC, agrafix commented on src/TW/Loader.hs
> +import Prelude
?

2017-06-09 13:45 UTC, agrafix commented on src/TW/Parser.hs
> +import Prelude
?

2017-06-09 13:45 UTC, agrafix commented on src/TW/Types.hs
> +import Prelude
?

2017-06-09 13:45 UTC, agrafix commented on src/TW/Utils.hs
> +import Prelude
?

2017-06-14 18:52 UTC, ajnsit commented on app/Main.hs
> +import Prelude
It's not, I just like having explicit Prelude imports and they snuck in. I'll remove them.

2017-06-14 20:55 UTC, agrafix commented
Great, thank you, this looks good :-)

2017-06-14 20:55 UTC, merged